public class App {
    public static void main(String[] args) throws Exception {
        int A = 5;
        int B = 8;
        // System.out.println(A); memanggil variabel A
        // System.out.println(B); memanggil variabel B
        // System.out.println(A - B); melakukan pengurangaan variabel A dikurang variabel B
        System.out.println(A);
        System.out.println(B);
        System.out.println(A - B);
    }
}
